@Backend_Development_LeMarconnes_Reserveringssysteem_HostAddress = http://localhost:5074

GET {{Backend_Development_LeMarconnes_Reserveringssysteem_HostAddress}}/weatherforecast/
Accept: application/json

###
